# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07\x65xample\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"+\n\x0fMessageResponse\x12\x18\n\x10response_content\x18\x01 \x01(\t2\xac\x01\n\x1d\x42idirectionalStreamingService\x12\x45\n\x11SendMessageStream\x12\x10.example.Message\x1a\x18.example.MessageResponse\"\x00(\x01\x30\x01\x12\x44\n\x14SendMessageNonStream\x12\x10.example.Message\x1a\x18.example.MessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=26
  _globals['_MESSAGE']._serialized_end=52
  _globals['_MESSAGERESPONSE']._serialized_start=54
  _globals['_MESSAGERESPONSE']._serialized_end=97
  _globals['_BIDIRECTIONALSTREAMINGSERVICE']._serialized_start=100
  _globals['_BIDIRECTIONALSTREAMINGSERVICE']._serialized_end=272
# @@protoc_insertion_point(module_scope)
